# Generated by Django 3.2.23 on 2023-11-26 06:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.FileField(upload_to='blog_image')),
                ('slug', models.SlugField(editable=False, null=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_az', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('name_ru', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_az', models.TextField(null=True)),
                ('question_en', models.TextField(null=True)),
                ('question_ru', models.TextField(null=True)),
                ('answer', models.TextField()),
                ('answer_az', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=1500, verbose_name='Saytın başlığı')),
                ('site_title_az', models.CharField(max_length=1500, null=True, verbose_name='Saytın başlığı')),
                ('site_title_en', models.CharField(max_length=1500, null=True, verbose_name='Saytın başlığı')),
                ('site_title_ru', models.CharField(max_length=1500, null=True, verbose_name='Saytın başlığı')),
                ('number', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə')),
                ('adress', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('adress_az', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('adress_en', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('adress_ru', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('working_hours', models.CharField(max_length=1000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1500, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=1500, verbose_name='Linkedin')),
                ('instagram', models.CharField(blank=True, max_length=1500, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Twitter')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('number_1', models.CharField(max_length=100, null=True, verbose_name='Elaqe Nomresi')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email daxil edin')),
            ],
            options={
                'verbose_name': 'Tənzimləmə',
                'verbose_name_plural': 'Ümumi Tənzimləmələr',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('short_intro', models.CharField(max_length=80, null=True, verbose_name='Short Intro size: 80')),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(editable=False, null=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('text', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_az', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('name_ru', models.CharField(max_length=1000, null=True)),
                ('image', models.FileField(upload_to='country_images')),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('content_az', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(editable=False, null=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='blog.category')),
            ],
        ),
    ]
