# Generated by Django 3.2.23 on 2023-11-26 06:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_az',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_az',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_intro_az',
            field=models.CharField(max_length=80, null=True, verbose_name='Short Intro size: 80'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_intro_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Short Intro size: 80'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_intro_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Short Intro size: 80'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_az',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_az',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_ru',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
