# Generated by Django 3.2.23 on 2023-11-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231126_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='adress_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_title_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_intro_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text_ru',
        ),
    ]
