# Generated by Django 3.2.21 on 2023-10-19 01:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.FileField(upload_to='blog_image')),
            ],
        ),
    ]
