# Generated by Django 3.2.23 on 2023-11-29 02:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231129_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='Event Images')),
                ('content', ckeditor.fields.RichTextField()),
                ('video', models.TextField()),
            ],
        ),
    ]
