# Generated by Django 3.2.21 on 2023-10-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_intro',
            field=models.CharField(max_length=80, null=True, verbose_name='Short Intro size: 80'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(editable=False, null=True, verbose_name='Slug'),
        ),
    ]
