# Generated by Django 3.2.23 on 2023-11-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video',
        ),
    ]
