# Generated by Django 3.2.21 on 2023-10-26 02:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231026_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(editable=False, null=True, verbose_name='Slug'),
        ),
    ]
