# Generated by Django 3.2.23 on 2023-11-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_event_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='Student Images')),
                ('country', models.CharField(max_length=1000)),
                ('major', models.CharField(max_length=1000)),
                ('slug', models.SlugField(editable=False, null=True, verbose_name='Slug')),
            ],
        ),
    ]
