# Generated by Django 3.2.21 on 2023-10-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
