# Generated by Django 3.2.22 on 2023-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=1500, verbose_name='Saytın başlığı')),
                ('number', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Nömrə')),
                ('adress', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('facebook', models.CharField(blank=True, max_length=1500, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=1500, verbose_name='Linkedin')),
                ('instagram', models.CharField(blank=True, max_length=1500, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Twitter')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('number_1', models.CharField(max_length=100, null=True, verbose_name='Elaqe Nomresi')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email daxil edin')),
            ],
            options={
                'verbose_name': 'Tənzimləmə',
                'verbose_name_plural': 'Ümumi Tənzimləmələr',
                'ordering': ['-id'],
            },
        ),
    ]
