# Generated by Django 3.2.22 on 2023-11-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='working_hours',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
